language: python

matrix:
  include:
    - python: 3.9
      env: TOXENV=py39-django111
    - python: 3.9
      env: TOXENV=py39-django20
    - python: 3.9
      env: TOXENV=py39-django21
    - python: 3.9
      env: TOXENV=py39-django22

branches:
    only:
        - master

install: pip install --quiet tox

# command to run tests
script: tox

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.9
