# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-29 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={'verbose_name': 'affiliate', 'verbose_name_plural': 'affiliates'},
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
